version: 2

models:
  - name: customers
    description: One record per customer
    columns:
      - name: customer_id
        description: Primary Key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not placed an order
  
  - name: stg_customers
    description: This model cleans up customer data
    columns:
      - name: customer_id
        description: Primary Key
        tests:
          - unique
          - not_null
  
  - name: stg_orders
    description: This model cleans up orders data
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              field: customer_id
              to: ref('stg_customers')