version: 2

sources:
  - name: dev
    tables:
      - name: hourly_air_quality
        tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - city
              - timestamp
  - name: prod
    tables:
      - name: hourly_air_quality
        tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - city
              - timestamp

models:
  - name: state_city_air_quality
    description: Air quality data by city and state. Composite PK = city + timestamp
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - city
            - timestamp
    columns:
      - name: state
        tests:
          - not_null
          - relationships:
              field: state
              to: ref('state_locations')
      - name: pollutant_value
        tests:
          - not_null

  - name: air_quality
    description: Hourly air quality data. Composite PK = city + timestamp
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - city
            - timestamp
    columns:
      - name: city
        tests:
          - not_null
      - name: timestamp
        description: Format of YYYY-MM-DD HH:MM:SS.
        tests:
          - not_null
      - name: pollutant
        description: Pollutant with the highest value is recorded
        tests:
          - accepted_values:
              values: ['PM10', 'PM2.5', 'NO2', 'SO2', 'CO2', 'O3', '']
      - name: pollutant_value
        tests:
          - not_null
      - name: unit
        tests:
          - accepted_values:
              values: ["ppm", "Î¼g/m3", ""]

  - name: stg_hourly_air_quality
    description: Removes duplicates, cleans data. Primary key is combination of city and timestamp.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - city
            - timestamp
    columns:
      - name: city
        tests:
          - not_null
      - name: timestamp
        description: Format of YYYY-MM-DD HH:MM:SS
        tests:
          - not_null
      - name: pollutant_value
        tests:
          - not_null
      - name: pollutant_symbol
        tests:
          - accepted_values:
              values: ["*", "**", "a", "b", "c", "d", "&"]