version: 2

models:
  - name: state_city_air_quality
    description: Air quality data by city and state. Composite PK = city + timestamp.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - city
            - timestamp
    columns:
      - name: state
        tests:
          - not_null
          - relationships:
              field: state
              to: ref('state_locations')
      - name: pollutant_value
        tests:
          - not_null

  - name: air_quality
    description: Hourly air quality data. Composite PK = city + timestamp.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - city
            - timestamp
    columns:
      - name: city
        tests:
          - not_null
      - name: timestamp
        description: Format of YYYY-MM-DD HH:MM:SS.
        tests:
          - not_null
      - name: pollutant
        description: There are different sensors which track different pollutants. Only the highest valued pollutant is recorded.
        tests:
          - accepted_values:
              values: ['PM10', 'PM2.5', 'NO2', 'SO2', 'CO2', 'O3', '']
      - name: pollutant_value
        description: The station records several values from different sensors, only the highest value is recorded as air quality reading.
        tests:
          - not_null
      - name: unit
        description: Unit for the air quality reading of the sensor.
        tests:
          - accepted_values:
              values: ["ppm", "Î¼g/m3", ""]