version: 2

models:
  - name: air_quality
    description: Hourly air quality data. Composite PK = city + datetime.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - location
            - datetime
    columns:
      - name: location
        tests:
          - not_null
      - name: datetime
        description: Format of YYYY-MM-DD HH:MM:SS.
        tests:
          - not_null
      - name: pollutant
        description: There are different sensors which track different pollutants. Only the highest valued pollutant is recorded.
        tests:
          - accepted_values:
              values: ['PM10', 'PM2.5', 'NO2', 'SO2', 'CO2', 'O3', 'multi-pollutant', 'CO', '']
      - name: pollutant_value
        description: The station records several values from different sensors, only the highest value is recorded as air quality reading.
        tests:
          - not_null
      # - name: unit
      #   description: Unit for the air quality reading of the sensor.
      #   tests:
      #     - accepted_values:
      #         values: ["ppm", "Î¼g/m3", ""]

  - name: weather
    description: "Hourly data from weather API"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - location
            - datetime
    columns:
      - name: location
        tests:
          - not_null
      - name: datetime
        description: Format of YYYY-MM-DD HH:MM:SS.
        tests:
          - not_null

  - name: full_weather
    description: "Hourly data for all envinronmental factors, combining air quality & weather"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - location
            - datetime
    columns:
      - name: location
        tests:
          - not_null
          - relationships:
              field: identifying_location
              to: ref('state_locations')
      - name: datetime
        description: Format of YYYY-MM-DD HH:MM:SS.
        tests:
          - not_null