version: 2

seeds:
  - name: city_states
    description: Mapping of cities and their state
    columns:
      - name: city
        description: Primary Key
        tests:
          - unique
          - not_null
      - name: state
        tests:
          - unique
          - not_null

  - name: city_places
    description: Mapping of places and their cities
    columns:
      - name: place
        tests:
          - unique
          - not_null
      - name: city
        tests:
          - not_null
          - relationships:
              field: city
              to: ref('city_states')

  - name: state_locations
    description: Certain MCAQM stations do not have accurate lat & long values, eg. Kota Kinabalu Station
    columns:
      - name: identifying_location
        tests:
          - unique
          - not_null
      - name: place
        tests:
          - not_null
          - relationships:
              field: place
              to: ref('city_places')
      - name: latitude
        tests:
          - not_null
      - name: longitude
        tests:
          - not_null
      - name: postcode
      - name: ICAO
        description: "The airport code of this location"
      - name: pwstation
        description: "Personal weather station code"
      - name: address
        description: "Address of the location in dictionary / json format"

  - name: air_quality_warning
    columns:
      - name: label
        description: "Represents the severity of the pollution value"
        tests:
          - accepted_values:
              values: ["Good", "Moderate", "Unhealthy", "Unhealthy for sensitive groups", "Very unhealthy", "Hazardous"]
      - name: pollutant
        description: Pollutant type
        tests:
          - accepted_values:
              values: ["PM2.5", "PM10", "SO2", "CO2", "O3", "NO2", "Unidentified", "multi-pollutant", "CO"]
      - name: should_report
        description: "If true, an air quality value at this level should be notified to authorities and users"
          
  - name: air_quality_indicators
    description: A mapping for each pollutant, unit and label.

  - name: uv_info
    description: "UV information for weather"
    columns:
      - name: uv_level
        description: "Represents upper limit. Eg: uv_value of 2 indicates uv within 0-2"