version: 2

seeds:
  - name: city_states
    description: Mapping of cities and their state
    columns:
      - name: city
        description: Primary Key
        tests:
          - unique
          - not_null
      - name: state
        tests:
          - not_null

  - name: state_locations
    description: Certain MCAQM stations do not have accurate lat & long values, eg. Kota Kinabalu Station
    columns:
      - name: identifying_location
        tests:
          - unique
          - not_null
      - name: city
        tests:
          - not_null
          - relationships:
              field: city
              to: ref('city_states')
      - name: latitude
        tests:
          - not_null
      - name: longitude
        tests:
          - not_null
      - name: ICAO
        description: "The airport code of this location"

  - name: air_quality_warning
    columns:
      - name: limit
        description: "Represents the upper limit of air quality value of this polutant. Eg: 0-50, 51-100, 101-150, 151-200, 201-300, 301-500"
      - name: should_report
        description: "If true, an air quality value at this level should be notified to authorities and users"
          
  - name: air_quality_indicators
    description: A mapping for each pollutant, unit and label.

  - name: uv
    description: "UV information for weather"
    columns:
      - name: uv_level
        description: "Represents upper limit. Eg: uv_value of 2 indicates uv within 0-2"