version: 2

seeds:
  - name: state_locations
    columns:
      - name: location
        tests:
          - unique
          - not_null
      - name: state
        tests:
          - not_null

  - name: air_quality_warning
    columns:
      - name: limit
        description: "Represents the upper limit of air quality value of this polutant. Eg: 0-50, 51-100, 101-150, 151-200, 201-300, 301-500"
      - name: should_report
        description: "If true, an air quality value at this level should be notified to authorities and users"
          
  - name: air_quality_indicators
    description: A mapping for each pollutant, unit and label.