version: 2

sources:
  - name: dev
    tables:
      - name: hourly_air_quality
        columns:
          - name: location
            tests:
              - not_null
          - name: datetime
            tests:
              - not_null
          - name: value
            tests:
              - not_null     
      - name: hourly_weather
        columns:
          - name: weather_station
            tests:
              - not_null
          - name: datetime
            tests:
              - not_null
      - name: hourly_pws_weather
        columns:
          - name: datetime
            tests:
              - not_null
          - name: weather_station
            description: "Personal weather station location"
            tests:
              - not_null
  - name: prod
    tables:
      - name: hourly_air_quality
        # - dbt_utils.unique_combination_of_columns:
        #     combination_of_columns:
        #       - location
        #       - timestamp
      - name: hourly_weather
        columns:
          - name: weather_station
      - name: hourly_pws_weather
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - datetime
                - weather_station
        columns:
          - name: datetime
            tests:
              - not_null
          - name: weather_station
            description: "Personal weather station location"
            tests:
              - not_null


models:
  - name: stg_hourly_air_quality
    description: Removes duplicates, cleans data. Primary key is combination of city and datetime.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - location
            - datetime
    columns:
      - name: location
        tests:
          - not_null
          - relationships:
              field: identifying_location
              to: ref('state_locations')
      - name: datetime
        description: Format of YYYY-MM-DD HH:MM:SS
        tests:
          - not_null
      - name: pollutant_value
        description: Air Quality reading from the station.
        tests:
          - not_null
      - name: pollutant_symbol
        description: The station records several values from different sensors, only the highest value is recorded as air quality reading.
        tests:
          - accepted_values:
              values: ["*", "**", "a", "b", "c", "d", "&", null, ""]

  - name: stg_hourly_weather
    description: Sets datatypes and ensures no extreme values
    columns:
      - name: datetime
        tests:
          - not_null
      - name: weather_station
        tests:
          - not_null
          - relationships:
              to: ref('state_locations')
              field: ICAO

  - name: stg_hourly_pws_weather
    description: Table for personal weather station, cleaning and eliminating outliers
    columns:
      - name: date