version: 2

sources:
  - name: dev
    tables:
      - name: hourly_air_quality
      - name: hourly_weather
  - name: prod
    tables:
      - name: hourly_air_quality
        # - dbt_utils.unique_combination_of_columns:
        #     combination_of_columns:
        #       - city
        #       - timestamp
      - name: hourly_weather


models:
  - name: stg_hourly_air_quality
    description: Removes duplicates, cleans data. Primary key is combination of city and datetime.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - city
            - datetime
    columns:
      - name: city
        tests:
          - not_null
      - name: datetime
        description: Format of YYYY-MM-DD HH:MM:SS
        tests:
          - not_null
      - name: pollutant_value
        description: Air Quality reading from the station.
        tests:
          - not_null
      - name: pollutant_symbol
        description: The station records several values from different sensors, only the highest value is recorded as air quality reading.
        tests:
          - accepted_values:
              values: ["*", "**", "a", "b", "c", "d", "&"]

  - name: stg_hourly_weather
    description: Sets datatypes and ensures no extreme values
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - weather_station
            - datetime
    columns:
      - name: datetime
        tests:
          - not_null
      - name: weather_station
        tests:
          - not_null
          - relationships:
              to: ref('stations')
              field: ICAO