name: Python to run prefect-agent daily at 1.00am Malaysian time
on: 
  schedule:
    # Cron jobs are in UTC time, which is 8 hours b4 Malaysia time, hence 1am is 5pm in UTC.
    - cron: "0 17 * * *"
jobs:
  run-agent:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      uses: szenius/set-timezone@v1.2
      with:
        timezoneWindows: "Singapore Standard Time"

      - name: Keep workflow alive (if > 50days)
        uses: gautamkrishnar/keepalive-workflow@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "data-owner@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Run prefect agent
        run: prefect agent start --run-once --pool default-agent-pool