name: Update Air Quality Database

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  update_symbol_list:
    name: Update air quality from stations periodically
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          PROJECT: ${{ secrets.PROJECT }}
          DATASET: ${{ secrets.DATASET }}
          TABLE_STATE: ${{ secrets.TABLE_STATE }}
          TABLE_STATE_ID: ${{ secrets.TABLE_STATE_ID }}
          TABLE_AIR_QUALITY: ${{ secrets.TABLE_AIR_QUALITY }}
          TABLE_AIR_QUALITY_ID: ${{ secrets.TABLE_AIR_QUALITY_ID }}
        run: |
          python main.py
